import { environment } from '../../environments/environment';

const BASE_URLS: any = environment.baseUrl;

const BASE_POINTS = {
  AUTH: BASE_URLS.SKILL_UP + "/Auth",
  USER: BASE_URLS.SKILL_UP + "/Users",
  COURSE: BASE_URLS.SKILL_UP + "/Course",
  LESSON: BASE_URLS.SKILL_UP + "/Lessons",
  SUB_LESSON: BASE_URLS.SKILL_UP + "/SubLessons",
  QUIZ: BASE_URLS.SKILL_UP + "/Quizzes",
  DOCUMENT: BASE_URLS.SKILL_UP + "/Documents",
  AI: BASE_URLS.SKILL_UP + "/AI",
  LOOKUP: BASE_URLS.SKILL_UP + "/Lookups",
}

export const API_URLS = {
  
  //API Auth
  LOGIN: BASE_POINTS.AUTH + "/login",
  LOGOUT: BASE_POINTS.AUTH + "/logout-all",
  REFRESH_TOKEN: BASE_POINTS.AUTH + "/refresh-token",
  REVOKE_TOKEN: BASE_POINTS.AUTH + "/revoke-token",
  USER_INFO: BASE_POINTS.USER + "/me",

  //Api User
  GET_USERS_ADMIN_LIST: BASE_POINTS.USER,
  GET_USERS_MANAGER_LIST: BASE_POINTS.USER + "/manager",
  GET_USER_BY_ID: BASE_POINTS.USER,
  CREATE_USER: BASE_POINTS.USER + "/create",
  UPDATE_USER: BASE_POINTS.USER + "/update",
  UPDATE_USER_ROLE_STATUS: BASE_POINTS.USER ,
  DELETE_USER: BASE_POINTS.USER + "/delete",
  UPLOAD_AVATAR: BASE_POINTS.USER,
  DOWNLOAD_TEMPLATE: BASE_POINTS.USER + "/import-template",
  IMPORT_EXCEL: BASE_POINTS.USER + "/import-excel",
  LEVELS: BASE_POINTS.USER + "/levels",

  //API Lesson
  GET_LESSONS: BASE_POINTS.COURSE,
  LESSON: BASE_POINTS.LESSON,
  REORDER_LESSONS: BASE_POINTS.LESSON + "/reorder",

  //API SubLesson
  SUB_LESSON: BASE_POINTS.SUB_LESSON,

  //API Course
  GET_COURSES_CREATOR_ADMIN_MANAGER: BASE_POINTS.COURSE + "/creator-admin-manager",
  GET_COURSES_CREATOR_LECTURER: BASE_POINTS.COURSE + "/lecturer/me",
  GET_COURSES: BASE_POINTS.COURSE + "/get-all",
  COURSE: BASE_POINTS.COURSE,
  GET_COURSES_USER_VIEW: BASE_POINTS.COURSE + "/user/view",

  //API Quiz
  GET_QUIZZES: BASE_POINTS.QUIZ + "/get-all",
  GET_QUIZ_BY_ID: BASE_POINTS.QUIZ + "/get-by-id",
  CREATE_QUIZ: BASE_POINTS.QUIZ + "/create",
  UPDATE_QUIZ: BASE_POINTS.QUIZ + "/update",
  DELETE_QUIZ: BASE_POINTS.QUIZ + "/delete",

  //API Document
  UPLOAD_DOCUMENT: BASE_POINTS.DOCUMENT + "/upload",
  GET_DOCUMENTS: BASE_POINTS.DOCUMENT + "/course",
  GET_DOCUMENT_BY_ID: BASE_POINTS.DOCUMENT,
  UPDATE_DOCUMENT: BASE_POINTS.DOCUMENT,
  DELETE_DOCUMENT: BASE_POINTS.DOCUMENT,
  DOWNLOAD_DOCUMENT: BASE_POINTS.DOCUMENT,

  //API AI
  GET_AI_CHAT: BASE_POINTS.AI + "/chat",

  //API Lookup
  GET_COURSE_TYPES: BASE_POINTS.LOOKUP + "/course-types",
  GET_LEVELS: BASE_POINTS.LOOKUP + "/user-levels",
}