import { environment } from '../../environments/environment';

const BASE_URLS: any = environment.baseUrl;

const BASE_POINTS = {
  AUTH: BASE_URLS.SKILL_UP + "/Auth",
  USER: BASE_URLS.SKILL_UP + "/Users",
  COURSE: BASE_URLS.SKILL_UP + "/Course",
  LESSON: BASE_URLS.SKILL_UP + "/Lessons",
  QUIZ: BASE_URLS.SKILL_UP + "/Quizzes",
  DOCUMENT: BASE_URLS.SKILL_UP + "/Documents",
}

export const API_URLS = {
  
  //API Auth
  LOGIN: BASE_POINTS.AUTH + "/login",
  LOGOUT: BASE_POINTS.AUTH + "/logout-all",
  REFRESH_TOKEN: BASE_POINTS.AUTH + "/refresh-token",
  REVOKE_TOKEN: BASE_POINTS.AUTH + "/revoke-token",
  USER_INFO: BASE_POINTS.USER + "/me",

  //Api User
  GET_USERS_ADMIN_LIST: BASE_POINTS.USER,
  GET_USERS_MANAGER_LIST: BASE_POINTS.USER + "/manager",
  GET_USER_BY_ID: BASE_POINTS.USER,
  CREATE_USER: BASE_POINTS.USER + "/create",
  UPDATE_USER: BASE_POINTS.USER + "/update",
  UPDATE_USER_ROLE_STATUS: BASE_POINTS.USER ,
  DELETE_USER: BASE_POINTS.USER + "/delete",
  UPLOAD_AVATAR: BASE_POINTS.USER,
  DOWNLOAD_TEMPLATE: BASE_POINTS.USER + "/import-template",
  IMPORT_EXCEL: BASE_POINTS.USER + "/import-excel",

  //API Lesson
  GET_LESSONS: BASE_POINTS.COURSE,
  CREATE_LESSON: BASE_POINTS.LESSON + "/create",
  UPDATE_LESSON: BASE_POINTS.LESSON + "/update",
  DELETE_LESSON: BASE_POINTS.LESSON + "/delete",

  //API Course
  GET_COURSES_CREATOR: BASE_POINTS.COURSE + "/creator",
  GET_COURSES: BASE_POINTS.COURSE + "/get-all",
  GET_COURSE_BY_ID: BASE_POINTS.COURSE + "/get-by-id",
  CREATE_COURSE: BASE_POINTS.COURSE + "/create",
  UPDATE_COURSE: BASE_POINTS.COURSE + "/update",
  DELETE_COURSE: BASE_POINTS.COURSE + "/delete",
  
  //API Quiz
  GET_QUIZZES: BASE_POINTS.QUIZ + "/get-all",
  GET_QUIZ_BY_ID: BASE_POINTS.QUIZ + "/get-by-id",
  CREATE_QUIZ: BASE_POINTS.QUIZ + "/create",
  UPDATE_QUIZ: BASE_POINTS.QUIZ + "/update",
  DELETE_QUIZ: BASE_POINTS.QUIZ + "/delete",

  //API Document
  UPLOAD_DOCUMENT: BASE_POINTS.DOCUMENT + "/upload",
  GET_DOCUMENTS: BASE_POINTS.DOCUMENT + "/course",
  GET_DOCUMENT_BY_ID: BASE_POINTS.DOCUMENT,
  UPDATE_DOCUMENT: BASE_POINTS.DOCUMENT,
  DELETE_DOCUMENT: BASE_POINTS.DOCUMENT,
  DOWNLOAD_DOCUMENT: BASE_POINTS.DOCUMENT,
}